### ISSUE TITLE
CORS error on separate machines

### ISSUE THREAD

**Issue by Navdeepuniyal** [pfertyk/webrtc-working-example#10]
I am using two separate machines to run the WebRTC example but the protocol seems to be failing at the signalling level
I am getting following error in firefox:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://<IP Address>:9999/socket.io/?EIO=3&transport=polling&t=NTA21tH. (Reason: CORS request did not succeed).

I followed the blog and did enable the following flags:

media.devices.insecure.enabled
media.getusermedia.insecure.enabled

Is something else needs to be changed?

**Comment by pfertyk** [comment]
Hi! I can see that you closed this issue. Does it mean you've found a solution?

**Comment by Navdeepuniyal** [comment]
Hi, sorry for that. It was a network issue between the two machines which was causing this error.
