### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Barbozah** [pfertyk/webrtc-working-example#2]
# step by step
```bash
git clone https://github.com/pfertyk/webrtc-working-example.git
cd  webrtc-working-example
python3 -m signaling/requirements.txt
python3 server.py
```
# in another terminal
```bash
cd ./web
python3 -m http.server 7000
```
# in browser
```
localhost:7000
```
# received in browser console and network
http://localhost:9999/socket.io/?EIO=3&transport=polling&t=N4tObbg (failed) from socket.io.js
...?EIO=3&transport=polling&t=... (failed) from socket.io.js
...?EIO=3&transport=polling&t=... (failed) from socket.io.js
...

**Comment by pfertyk** [comment]
Hi!

Thanks for reporting this. I just downloaded a fresh repo and it worked without problems. The only message I got in web browser's console was:

```
Source map error: Error: request failed with status 404
Resource URL: http://localhost:7000/socket.io.js
Source Map URL: socket.io.js.map
```

But that didn't stop the application from running in any way.

Can you confirm that you are using Firefox? I haven't tested this example on other browsers, so there might be unresolved issues. Can you confirm that after entering `localhost:7000` in your browser you were asked for camera/microphone permissions and that you've granted them?

Also, just to be clear, I assume that the first part of setup instructions that you've used was:

```
git clone https://github.com/pfertyk/webrtc-working-example.git
cd webrtc-working-example/signaling
pip3 install -r requirements.txt
python3 server.py
```

I'm sure it was just a typo in your message, but I'd like to confirm ;)

**Comment by Barbozah** [comment]
Works fine in Mozilla Browser.
