### ISSUE TITLE
Echo local sound

### ISSUE THREAD

**Issue by xituorp** [pfertyk/webrtc-working-example#36]
Problem local sound echoing.
Solution proposed: add muted to video local stream in /web/index.html:`
    <video id="localStream" autoplay playsinline muted></video>`

**Comment by pfertyk** [comment]
Hi and thanks for reaching out!

This is a very good idea, and in fact there is already an issue for this: #30 . The full solution here is to add a button (both to web and mobile apps) to turn off the sound and/or video. I will see what I can do about it ;)

Cheers,
Paweł

**Comment by pfertyk** [comment]
Hi again!

Today I've made some progress with this task, I just need to clean it up and push the code :) It should be solved soon ;)

Cheers,
Paweł

**Comment by pfertyk** [comment]
![Screenshot from 2022-11-18 22-47-11](https://user-images.githubusercontent.com/11876747/202808632-210ec4ed-76d9-428f-bb75-47ffbf03899c.png)

Hi!

I've added a button to toggle the mic status, and it's disabled by default. So now there should be no local sound feedback when you start the application. I hope this solves the issue ;)

Cheers,
Paweł
