### ISSUE TITLE
favicon.ico missing

### ISSUE THREAD

**Issue by amarco** [pfertyk/webrtc-working-example#38]
when I run it I get a missing file, can it be included?

C:\WinPython\webrtc\webrtc-working-example\web>python -m http.server 7000
Serving HTTP on :: port 7000 (http://[::]:7000/) ...
::1 - - [29/Nov/2022 17:54:18] "GET / HTTP/1.1" 304 -
::1 - - [29/Nov/2022 17:54:18] "GET /style.css HTTP/1.1" 304 -
::1 - - [29/Nov/2022 17:54:18] "GET /socket.io.js HTTP/1.1" 304 -
::1 - - [29/Nov/2022 17:54:18] "GET /main.js HTTP/1.1" 304 -
::1 - - [29/Nov/2022 17:54:18] code 404, message File not found
::1 - - [29/Nov/2022 17:54:18] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by pfertyk** [comment]
Hi! I'll take a look at this later, I think it should be easy to fix ;) Either way, this error is not critical and will not stop WebRTC from working in any way ;)

**Comment by pfertyk** [comment]
Icon added :) I realized that I use mostly Firefox, and it doesn't check for favicon by default. However, Chromium does, and I don't want any unnecessary errors here ;P
