### ISSUE TITLE
socketIO version problems?

### ISSUE THREAD

**Issue by csik** [pfertyk/webrtc-working-example#6]
Hi thanks for a nice post, but I'm not successful in running the repo. Docker successfully launches all three servers but when a firefox browser opens, and cam and mic permissions are granted, the signaling server generates:

`The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)`

and on the browser side there are a lot of 400 errors:
GEThttp://localhost:9999/socket.io/?EIO=3&transport=polling&t=NQlTBQQ
[HTTP/1.1 400 Bad Request 2ms]

Thoughts?

**Comment by csik** [comment]
Not sure why, but docker was configuring for python2.6, with a fairly old version of socketio, upgraded to py2.9 and socketio 3 and it's working. Thanks!

**Comment by pfertyk** [comment]
Hi! I'm glad you've found a solution :) I tested the code with Python3, and I'm surprised that Docker by default used Python2. I'll create a task to fix it later.

Thanks for reporting this and for describing a fix! :)

**Comment by csik** [comment]
Apologies! That was a typo... it should have been 3.6. I don't have 3.6 on my system, so I was surprised it chose that. In any case, on a Mac running 10.15.7 the docker python_socketio and the socket.io.js were incompatible, but everything worked when I upgraded them to matching releases.

![image](https://user-images.githubusercontent.com/1150692/103326801-ff252c80-4a1f-11eb-8bbd-c368b4df9eb3.png)
